# fly.toml app configuration file generated for ssh-tictactoe-laurenzguevara on 2025-06-03T15:35:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssh-tictactoe-laurenzguevara'
primary_region = 'lhr'

[build]

[env]
  PORT = '23234'

[[services]]
  internal_port = 23234
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  [[services.ports]]
    port = 22

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "ssh_key"
  destination = "/ssh-tictactoe-keys"
